permalink: /brodin/:year/:month/:title
include: ['_pages','portfolio']
highlighter: rouge
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "arquivos" # an empty string here means all files in the project
    values:
      layout: "special"
  -
    scope:
      path: "teste" # an empty string here means all files in the project
      type: "posts" 
    values:
      layout: "special"
  -
    scope:
      path: "portfolio" # an empty string here means all files in the project
      type: "posts" 
    values:
      layout: "portfolio"  
      permalink: /portfolio/:title        