defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
  -
    scope:
      path: "arquivos" # an empty string here means all files in the project
    values:
      layout: "special"
  -
    scope:
      path: "teste" # an empty string here means all files in the project
      type: "posts" 
    values:
      layout: "special"      