permalink: /brodin/:year/:month/:title
include: ['_pages','portfolio']
highlighter: rouge
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "arquivos" 
    values:
      layout: "special"
  -
    scope:
      path: "teste" 
      type: "posts" 
    values:
      layout: "special"
  -
    scope:
      path: "portfolio" 
      type: "posts" 
    values:
      layout: "portfolio"  
      permalink: /portfolio/:title